<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Post; 
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage; 

class PostController extends Controller
{
    public function index()
    {
        // 1. Ambil semua data berita dari database
        $posts = Post::latest()->paginate(10); // Ambil data terbaru, 10 per halaman

        // 2. Kirim data ke view
        return view('admin.posts.index', compact('posts'));
    }

    public function create()
    {
        // Cukup tampilkan view form-nya
        return view('admin.posts.create');
    }

    
    public function store(Request $request)
    {
        // 1. Validasi Input
        $validatedData = $request->validate([
            'judul' => 'required|string|max:255',
            'isi'  => 'required|string',
            'gambar' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:25000', // Boleh kosong, hrs gambar, max 25MB
        ]);

        // 2. Handle File Upload (jika ada)
        $imagePath = null;
        if ($request->hasFile('gambar')) {
            // Simpan gambar di 'storage/app/public/posts-gambar'
            // 'public' adalah disk
            $imagePath = $request->file('gambar')->store('posts-gambar', 'public');
        }

        // 3. Buat Slug dari Judul
        $slug = Str::slug($validatedData['judul'], '-');
        // 4. Simpan ke Database
        Post::create([
            'judul'     => $validatedData['judul'],
            'slug'      => $slug,
            'isi'      => $validatedData['isi'],
            'gambar'     => $imagePath,
            'tanggal_dipublikasikan' => now() // Langsung kita publish
            // user_id nanti bisa ditambahkan jika perlu
        ]);

        // 5. Redirect kembali ke halaman index dengan pesan sukses
        return redirect()->route('admin.berita.index')
                        ->with('success', 'Berita baru berhasil ditambahkan!');
    }

   
    public function show(string $id)
    {
        //
    }

    
    public function edit(Post $beritum)
    {
        // Route parameter generated by Route::resource('berita', ...) becomes {beritum}
        // keep view variable name as 'berita' for consistency with views
        return view('admin.posts.edit', ['berita' => $beritum]);
    }


    public function update(Request $request, Post $beritum)
    {
        // 1. Validasi Input (sesuai nama kolom di tabel: judul, isi, gambar)
        $validatedData = $request->validate([
            'judul' => 'required|string|max:255',
            'isi'   => 'required|string',
            'gambar' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:25000', // Boleh kosong, hrs gambar, max 25MB
        ]);

        // 2. Handle File Upload (jika ada file baru)
        if ($request->hasFile('gambar')) {
            $imagePath = $request->file('gambar')->store('posts-images', 'public');
            $validatedData['gambar'] = $imagePath;
        }

        // 3. Update Slug dari Judul
        $validatedData['slug'] = Str::slug($validatedData['judul'], '-');

        // 4. Update ke Database (hanya kolom yang valid dan ada di $fillable)
         $beritum->update($validatedData);

        // 5. Redirect kembali ke halaman index dengan pesan sukses
        return redirect()->route('admin.berita.index')
                        ->with('success', 'Berita berhasil diperbarui!');
    }

    
    public function destroy(Post $beritum)
    {
        // Hapus gambar terkait dari storage (jika ada)
        if ($beritum->gambar) {
            Storage::disk('public')->delete($beritum->gambar);
        }
        
        // Hapus berita dari database
        $beritum->delete();
        
        return redirect()->route('admin.berita.index')->with('success', 'Berita berhasil dihapus!');
    }
}
